import { useNavigate } from 'react-router-dom'

function ProductBuilderStep4() {
  const navigate = useNavigate()

  return (
    <section className="mx-auto max-w-4xl rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <p className="text-xs font-semibold uppercase tracking-[0.14em] text-blue-700">Step 4 of 4</p>
      <h1 className="mt-2 text-2xl font-bold text-slate-900">Review & Confirm</h1>
      <p className="mt-1 text-sm text-slate-600">Validate configuration summary and create your manufacturing request.</p>

      <div className="mt-6 space-y-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-700">
        <p>Product type, packaging, branding, and compliance settings are ready.</p>
        <p>Estimated EXW cost and timeline generated by AI optimization model.</p>
      </div>

      <div className="mt-6 flex items-center justify-between">
        <button className="text-sm font-semibold text-slate-500" onClick={() => navigate('/product-builder/step-3')} type="button">Back</button>
        <button className="rounded-lg bg-blue-700 px-4 py-2 text-sm font-semibold text-white" onClick={() => navigate('/orders')} type="button">Create Order Draft</button>
      </div>
    </section>
  )
}

export default ProductBuilderStep4
